# GENERAL SETTINS

cluster.name:    "joystream_elastic"
node.name:       "joystream"
#node.attr.zone:  "my-zone"

#node.data: true
#node.master: true

network.host: 0.0.0.0

http.port: 9200
#transport.port: 9300
#server.publicBaseUrl: http://elastic_joystream.yyagi.cloud:5601
bootstrap.memory_lock: true
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false
http.cors.enabled: "true"
http.cors.allow-origin: "*"
#xpack.security.transport.ssl.client_authentication: required
script.allowed_types: inline
xpack.license.self_generated.type: trial
xpack.security.authc:
  anonymous:
    username: anonymous_user
    roles: anonymous_system
    authz_exception: true
