version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    container_name: elasticsearch
    ports: 
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data      
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.2
    container_name: kibana
    ports: 
      - "5601:5601"
    environment:
      - PATH_DATA=/usr/share/kibana/data
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/data:/usr/share/kibana/data
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
volumes:
  data:
